version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - 8080:80
      - 4433:443
    volumes:
      - ./app:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/

  db:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ${TRIBE_MYSQL_DATA_DIR:-~/mysql_data_tribe}:/var/lib/mysql

volumes:
  dbdata:
    driver: local
